//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallOut_CAD.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CADIncidentMessage", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class CADIncidentMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DispatchDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallOut_CAD.ServiceReference1.IncidentUnits[] DispatchUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentAlarmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallOut_CAD.ServiceReference1.IncidentLocation IncidentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DispatchDateTime {
            get {
                return this.DispatchDateTimeField;
            }
            set {
                if ((this.DispatchDateTimeField.Equals(value) != true)) {
                    this.DispatchDateTimeField = value;
                    this.RaisePropertyChanged("DispatchDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallOut_CAD.ServiceReference1.IncidentUnits[] DispatchUnits {
            get {
                return this.DispatchUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.DispatchUnitsField, value) != true)) {
                    this.DispatchUnitsField = value;
                    this.RaisePropertyChanged("DispatchUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentAlarm {
            get {
                return this.IncidentAlarmField;
            }
            set {
                if ((this.IncidentAlarmField.Equals(value) != true)) {
                    this.IncidentAlarmField = value;
                    this.RaisePropertyChanged("IncidentAlarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallOut_CAD.ServiceReference1.IncidentLocation IncidentLocation {
            get {
                return this.IncidentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentLocationField, value) != true)) {
                    this.IncidentLocationField = value;
                    this.RaisePropertyChanged("IncidentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentNo {
            get {
                return this.IncidentNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentNoField, value) != true)) {
                    this.IncidentNoField = value;
                    this.RaisePropertyChanged("IncidentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentPriority {
            get {
                return this.IncidentPriorityField;
            }
            set {
                if ((this.IncidentPriorityField.Equals(value) != true)) {
                    this.IncidentPriorityField = value;
                    this.RaisePropertyChanged("IncidentPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentTitle {
            get {
                return this.IncidentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentTitleField, value) != true)) {
                    this.IncidentTitleField = value;
                    this.RaisePropertyChanged("IncidentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentType {
            get {
                return this.IncidentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentTypeField, value) != true)) {
                    this.IncidentTypeField = value;
                    this.RaisePropertyChanged("IncidentType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncidentLocation", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class IncidentLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncidentUnits", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class IncidentUnits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallsignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitCurrentStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitHomeStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Callsign {
            get {
                return this.CallsignField;
            }
            set {
                if ((object.ReferenceEquals(this.CallsignField, value) != true)) {
                    this.CallsignField = value;
                    this.RaisePropertyChanged("Callsign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromStatus {
            get {
                return this.FromStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FromStatusField, value) != true)) {
                    this.FromStatusField = value;
                    this.RaisePropertyChanged("FromStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitCurrentStation {
            get {
                return this.UnitCurrentStationField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitCurrentStationField, value) != true)) {
                    this.UnitCurrentStationField = value;
                    this.RaisePropertyChanged("UnitCurrentStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitHomeStation {
            get {
                return this.UnitHomeStationField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitHomeStationField, value) != true)) {
                    this.UnitHomeStationField = value;
                    this.RaisePropertyChanged("UnitHomeStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitLocation {
            get {
                return this.UnitLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitLocationField, value) != true)) {
                    this.UnitLocationField = value;
                    this.RaisePropertyChanged("UnitLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CADIncidentAck", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class CADIncidentAck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AckNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AckTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AckTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallOut_CAD.ServiceReference1.Tracking[] AckTrackingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodingIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AckNo {
            get {
                return this.AckNoField;
            }
            set {
                if ((this.AckNoField.Equals(value) != true)) {
                    this.AckNoField = value;
                    this.RaisePropertyChanged("AckNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AckTimeStamp {
            get {
                return this.AckTimeStampField;
            }
            set {
                if ((this.AckTimeStampField.Equals(value) != true)) {
                    this.AckTimeStampField = value;
                    this.RaisePropertyChanged("AckTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AckTotal {
            get {
                return this.AckTotalField;
            }
            set {
                if ((this.AckTotalField.Equals(value) != true)) {
                    this.AckTotalField = value;
                    this.RaisePropertyChanged("AckTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallOut_CAD.ServiceReference1.Tracking[] AckTracking {
            get {
                return this.AckTrackingField;
            }
            set {
                if ((object.ReferenceEquals(this.AckTrackingField, value) != true)) {
                    this.AckTrackingField = value;
                    this.RaisePropertyChanged("AckTracking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodingID {
            get {
                return this.CodingIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CodingIDField, value) != true)) {
                    this.CodingIDField = value;
                    this.RaisePropertyChanged("CodingID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tracking", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class Tracking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CADIncidentCodingStatus", Namespace="http://schemas.datacontract.org/2004/07/CallOut_CADServiceLib")]
    [System.SerializableAttribute()]
    public partial class CADIncidentCodingStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AckFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AckNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AckStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AckTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AckTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CallOut_CAD.ServiceReference1.Tracking AckTrackingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodingIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AckFrom {
            get {
                return this.AckFromField;
            }
            set {
                if ((object.ReferenceEquals(this.AckFromField, value) != true)) {
                    this.AckFromField = value;
                    this.RaisePropertyChanged("AckFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AckNo {
            get {
                return this.AckNoField;
            }
            set {
                if ((this.AckNoField.Equals(value) != true)) {
                    this.AckNoField = value;
                    this.RaisePropertyChanged("AckNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AckStatus {
            get {
                return this.AckStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AckStatusField, value) != true)) {
                    this.AckStatusField = value;
                    this.RaisePropertyChanged("AckStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AckTimeStamp {
            get {
                return this.AckTimeStampField;
            }
            set {
                if ((this.AckTimeStampField.Equals(value) != true)) {
                    this.AckTimeStampField = value;
                    this.RaisePropertyChanged("AckTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AckTotal {
            get {
                return this.AckTotalField;
            }
            set {
                if ((this.AckTotalField.Equals(value) != true)) {
                    this.AckTotalField = value;
                    this.RaisePropertyChanged("AckTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CallOut_CAD.ServiceReference1.Tracking AckTracking {
            get {
                return this.AckTrackingField;
            }
            set {
                if ((object.ReferenceEquals(this.AckTrackingField, value) != true)) {
                    this.AckTrackingField = value;
                    this.RaisePropertyChanged("AckTracking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodingID {
            get {
                return this.CodingIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CodingIDField, value) != true)) {
                    this.CodingIDField = value;
                    this.RaisePropertyChanged("CodingID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CallOut_CADServiceLib", ConfigurationName="ServiceReference1.CallOut_CADService", CallbackContract=typeof(CallOut_CAD.ServiceReference1.CallOut_CADServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface CallOut_CADService {
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/CADJoin", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/CADJoinResponse")]
        void CADJoin();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/CADJoin", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/CADJoinResponse")]
        System.Threading.Tasks.Task CADJoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/CADLeave", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/CADLeaveResponse")]
        void CADLeave();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/CADLeave", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/CADLeaveResponse")]
        System.Threading.Tasks.Task CADLeaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/GatewayJoin", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/GatewayJoinResponse")]
        void GatewayJoin();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/GatewayJoin", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/GatewayJoinResponse")]
        System.Threading.Tasks.Task GatewayJoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/GatewayLeave", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/GatewayLeaveResponse")]
        void GatewayLeave();
        
        [System.ServiceModel.OperationContractAttribute(Action="CallOut_CADServiceLib/CallOut_CADService/GatewayLeave", ReplyAction="CallOut_CADServiceLib/CallOut_CADService/GatewayLeaveResponse")]
        System.Threading.Tasks.Task GatewayLeaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/SendCADIncidentMsg")]
        void SendCADIncidentMsg(CallOut_CAD.ServiceReference1.CADIncidentMessage CADincidentmsg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/SendCADIncidentMsg")]
        System.Threading.Tasks.Task SendCADIncidentMsgAsync(CallOut_CAD.ServiceReference1.CADIncidentMessage CADincidentmsg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/AckCADIncidentMsg")]
        void AckCADIncidentMsg(CallOut_CAD.ServiceReference1.CADIncidentAck CADincidentack);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/AckCADIncidentMsg")]
        System.Threading.Tasks.Task AckCADIncidentMsgAsync(CallOut_CAD.ServiceReference1.CADIncidentAck CADincidentack);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/BroadcastIncidentCodingStatus")]
        void BroadcastIncidentCodingStatus(CallOut_CAD.ServiceReference1.CADIncidentCodingStatus incidentcodingstatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/BroadcastIncidentCodingStatus")]
        System.Threading.Tasks.Task BroadcastIncidentCodingStatusAsync(CallOut_CAD.ServiceReference1.CADIncidentCodingStatus incidentcodingstatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/IncidentCodingStatusQuery")]
        void IncidentCodingStatusQuery(string querycodingID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/IncidentCodingStatusQuery")]
        System.Threading.Tasks.Task IncidentCodingStatusQueryAsync(string querycodingID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/IncidentCodingStatusResponse")]
        void IncidentCodingStatusResponse(CallOut_CAD.ServiceReference1.CADIncidentAck codingstatusresponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/IncidentCodingStatusResponse")]
        System.Threading.Tasks.Task IncidentCodingStatusResponseAsync(CallOut_CAD.ServiceReference1.CADIncidentAck codingstatusresponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallOut_CADServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/RcvCADIncidentMsg")]
        void RcvCADIncidentMsg(CallOut_CAD.ServiceReference1.CADIncidentMessage CADincidentMsg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/UpdateCADIncidentAck")]
        void UpdateCADIncidentAck(CallOut_CAD.ServiceReference1.CADIncidentAck CADincidentack);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/UpdateIncidentCodingStatus")]
        void UpdateIncidentCodingStatus(CallOut_CAD.ServiceReference1.CADIncidentCodingStatus incidentcodingstatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/IncidentCodingStatus")]
        void IncidentCodingStatus(string querycodingID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="CallOut_CADServiceLib/CallOut_CADService/RcvIncidentCodingStatusResponse")]
        void RcvIncidentCodingStatusResponse(CallOut_CAD.ServiceReference1.CADIncidentAck codingstatusresponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CallOut_CADServiceChannel : CallOut_CAD.ServiceReference1.CallOut_CADService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallOut_CADServiceClient : System.ServiceModel.DuplexClientBase<CallOut_CAD.ServiceReference1.CallOut_CADService>, CallOut_CAD.ServiceReference1.CallOut_CADService {
        
        public CallOut_CADServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CallOut_CADServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CallOut_CADServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CallOut_CADServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CallOut_CADServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CADJoin() {
            base.Channel.CADJoin();
        }
        
        public System.Threading.Tasks.Task CADJoinAsync() {
            return base.Channel.CADJoinAsync();
        }
        
        public void CADLeave() {
            base.Channel.CADLeave();
        }
        
        public System.Threading.Tasks.Task CADLeaveAsync() {
            return base.Channel.CADLeaveAsync();
        }
        
        public void GatewayJoin() {
            base.Channel.GatewayJoin();
        }
        
        public System.Threading.Tasks.Task GatewayJoinAsync() {
            return base.Channel.GatewayJoinAsync();
        }
        
        public void GatewayLeave() {
            base.Channel.GatewayLeave();
        }
        
        public System.Threading.Tasks.Task GatewayLeaveAsync() {
            return base.Channel.GatewayLeaveAsync();
        }
        
        public void SendCADIncidentMsg(CallOut_CAD.ServiceReference1.CADIncidentMessage CADincidentmsg) {
            base.Channel.SendCADIncidentMsg(CADincidentmsg);
        }
        
        public System.Threading.Tasks.Task SendCADIncidentMsgAsync(CallOut_CAD.ServiceReference1.CADIncidentMessage CADincidentmsg) {
            return base.Channel.SendCADIncidentMsgAsync(CADincidentmsg);
        }
        
        public void AckCADIncidentMsg(CallOut_CAD.ServiceReference1.CADIncidentAck CADincidentack) {
            base.Channel.AckCADIncidentMsg(CADincidentack);
        }
        
        public System.Threading.Tasks.Task AckCADIncidentMsgAsync(CallOut_CAD.ServiceReference1.CADIncidentAck CADincidentack) {
            return base.Channel.AckCADIncidentMsgAsync(CADincidentack);
        }
        
        public void BroadcastIncidentCodingStatus(CallOut_CAD.ServiceReference1.CADIncidentCodingStatus incidentcodingstatus) {
            base.Channel.BroadcastIncidentCodingStatus(incidentcodingstatus);
        }
        
        public System.Threading.Tasks.Task BroadcastIncidentCodingStatusAsync(CallOut_CAD.ServiceReference1.CADIncidentCodingStatus incidentcodingstatus) {
            return base.Channel.BroadcastIncidentCodingStatusAsync(incidentcodingstatus);
        }
        
        public void IncidentCodingStatusQuery(string querycodingID) {
            base.Channel.IncidentCodingStatusQuery(querycodingID);
        }
        
        public System.Threading.Tasks.Task IncidentCodingStatusQueryAsync(string querycodingID) {
            return base.Channel.IncidentCodingStatusQueryAsync(querycodingID);
        }
        
        public void IncidentCodingStatusResponse(CallOut_CAD.ServiceReference1.CADIncidentAck codingstatusresponse) {
            base.Channel.IncidentCodingStatusResponse(codingstatusresponse);
        }
        
        public System.Threading.Tasks.Task IncidentCodingStatusResponseAsync(CallOut_CAD.ServiceReference1.CADIncidentAck codingstatusresponse) {
            return base.Channel.IncidentCodingStatusResponseAsync(codingstatusresponse);
        }
    }
}
